Jms
DarkendHall/Slutprojekt_Java_EE pull request #67
Opened 2022-03-29 15:32 UTC by OscarStjernfeldt

fix #10

2022-04-01 10:12 UTC, DarkendHall requested changes
Looks good, just need some test then I'll approve

2022-04-04 15:18 UTC, DarkendHall submitted a review, later dismissed

2022-04-04 15:46 UTC, ChristianLofqvist approved these changes

2022-04-04 15:46 UTC, DarkendHall approved these changes

2022-04-04 15:47 UTC, merged